### ISSUE TITLE
Kirin not polling feeds from contributors

### ISSUE THREAD

**Issue by rafampinto** [CanalTP/kirin#409]
I'm trying to use Kirin for GTFS-RT updates with the Navitia Docker Compose project, I have followed the guidelines in the respective "readme" files.

The changes i did were the following:

- In the docker-compose.yml file i added the following configurations to the kraken-default:

```yaml
kraken-default:
    ...
    environment:
      - KRAKEN_GENERAL_instance_name=default
      - KRAKEN_GENERAL_database=/srv/ed/output/default.nav.lz4
      - KRAKEN_GENERAL_is_realtime_enabled=true
      - KRAKEN_GENERAL_is_realtime_add_enabled=true
      - KRAKEN_GENERAL_is_realtime_add_trip_enabled=true
      - KRAKEN_GENERAL_kirin_timeout=180000
      - KRAKEN_BROKER_host=rabbitmq 
      - KRAKEN_BROKER_port=5672
      - KRAKEN_BROKER_username=guest
      - KRAKEN_BROKER_password=guest
      - KRAKEN_BROKER_exchange=navitia
      - KRAKEN_BROKER_rt_topics=realtime.ireland
```

- Added a contributor to poll trip updates from a local server, based on GTFS-RT protocol, that retrieves trip updates from https://developer.nationaltransport.ie/ with my credentials. So, I added a contributor with the following parameters in the body:
```json
{
    	"navitia_coverage": "default",
	"id": "realtime.ireland",
  	"feed_url": "http://localhost:8081/gtfsr",
  	"connector_type": "gtfs-rt",
    	"retrieval_interval": 20,
    	"is_active": true
}
```
Then, when I launch the containers everything things to be working but I do not see any logs on my server, showing the Kirin polling GTFS-RT feeds. Also, I provide the feeds on the server in .pb format.
I already tried to check both /status?heavy_checks=true and /health endpoints of Kirin and it does not show any error, instead the last_update field is empty (showing that is not polling any data).

Am I making anything wrong here, any guesses what could go wrong with this?
Because I'm trying to use a local instance of Navitia to provide GTFS and GTFS-RT data to a mobile application that I am developing in the context of my master's thesis.
